---
Name: hail-config
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: 'silverstripe-hail'
Firebrand\Hail\Api\Client:
  BaseApiUrl: 'https://hail.to/api/v1/'
  AuthorizationUrl: 'https://hail.to/oauth/authorise'
  RefreshRate: 86400
  EnableEmojiSupport: false
  OnlyFetchPublishedObjects: true
Firebrand\Hail\Pages\HailPageController:
  UseDefaultCss: true
Firebrand\Hail\Tasks\FetchRecurringTask:
  Emails: 'developers@firebrand.nz'
